tutorial = np.html()
  .head()
    .meta('', {charset: 'utf-8'}).up()
    .title('nope.js - tutorial').up()
    .link('', {type: 'stylesheet', rel: 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css' }).up()
  .up()
  .body()
    .h1('nope.js - tutorial').up()
    .div()
      .h2('Getting started').up()
      .p('').up()
    .up()
  .up()
